version: "3"
services:
  mysql-standalone-2:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=PlayerDetails
      - MYSQL_USER=vkm
      - MYSQL_PASSWORD=1234
    ports:
      - 3307:3306

  docker-springboot-cricket:
    image: docker-springboot-cricket:latest
    ports:
      - 9099:8080
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone-2